### PR TITLE
Update env vars in rocks

### PR DESCRIPTION
**Pull request by i-chvets**
# Description

There was an issue discovered with latest ROCKs that incorrectly stored notebooks: https://github.com/canonical/notebook-operators/issues/312

In order to resolve the issue environment variable HOME needs to be set properly.

#  Summary of changes:
- Set HOME environment variable and sync it with working-dir
- Updated version field to include dashes because of recent Rockcraft changes.

### CODE REVIEW

**Comment by NohaIhab** [comment]
Hi @i-chvets 
I tried out the jupyter-scipy rock but I still don't see the working directory as expected, and files do not persist when stopping the notebook
I published it to `charmedkubeflow/jupyter-scipy-test:v1.7.0-20.04-1` if you want to play around with it.

Note: I changed the version to have hyphens instead of underscores because of the rockcraft bug, and I think you should do that in your PR as well so we can publish it once merged.

**Comment by i-chvets** [comment]
Justed tested with the test ROCK image pushed to registry: https://hub.docker.com/r/charmedkubeflow/jupyter-pytorch-full-test/tags

Screenshot from 2023-10-31 10-32-46

@NohaIhab Could you verify on your end with the above ROCK image.

**Comment by SamirPS** [comment]
Hello

With @i-chvets image, I have the good PWD, but with @NohaIhab image, I have the wrong PWD. Noha, can you use ```rockcraft clean``` before rebuilding the image?

**Comment by NohaIhab** [comment]
Confirming the above, the published rock `charmedkubeflow/jupyter-pytorch-full-test:v1.7.0-20.04-1` has the right pwd and the files persist when stopping and starting the notebook.
Just a small comment, the user in a terminal created from a notebook is not the same as upstream, but I wouldn't block on this. I don't see it affecting the functionality.

**Review by NohaIhab — APPROVED** [review]

**Pull request merged**
